services:
  bitcoin-fullnode-exporter:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: bitcoin-fullnode-prometheus-exporter
    restart: unless-stopped

    network_mode: host

    env_file:
      - .env