{
 "title": "Bitcoin Core Fullnode",
 "description": "Monitoring dashboard for Bitcoin Core Fullnode.",
 "tags": [
  "bitcoin",
  "fullnode"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "network",
    "label": "Network",
    "query": {
     "query": "label_values(bitcoin_node_info{job=\"Bitcoin-Fullnode\"},network)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bitcoin_node_info{job=\"Bitcoin-Fullnode\", network=\"$network\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Chain",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bitcoin_node_info{job=\"Bitcoin-Fullnode\", network=\"$network\"}",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "RPC Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bitcoin_node_rpc_available{job=\"Bitcoin-Fullnode\", network=\"$network\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "TxIndex Enabled",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bitcoin_node_feature_enabled{job=\"Bitcoin-Fullnode\", network=\"$network\", feature=\"txindex\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Filter Index Enabled",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bitcoin_node_feature_enabled{job=\"Bitcoin-Fullnode\", network=\"$network\", feature=\"blockfilterindex\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peer Block Filters Enabled",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bitcoin_node_feature_enabled{job=\"Bitcoin-Fullnode\", network=\"$network\", feature=\"peerblockfilters\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bitcoin_node_uptime_seconds{job=\"Bitcoin-Fullnode\", network=\"$network\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Chain Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bitcoin_node_chain_transactions{job=\"Bitcoin-Fullnode\", network=\"$network\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Headers Synced",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  bitcoin_node_header_height{job=\"Bitcoin-Fullnode\", network=\"$network\"}\n  -\n  bitcoin_node_block_height{job=\"Bitcoin-Fullnode\", network=\"$network\"}\n) == 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TxIndex Synced",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bitcoin_node_index_synced{job=\"Bitcoin-Fullnode\", network=\"$network\", index=\"txindex\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Filter Index Synced",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bitcoin_node_index_synced{job=\"Bitcoin-Fullnode\", network=\"$network\", index=\"basic_block_filter_index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Is Archive",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bitcoin_node_pruned{job=\"Bitcoin-Fullnode\", network=\"$network\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blockchain Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bitcoin_node_chain_size_bytes{job=\"Bitcoin-Fullnode\", network=\"$network\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bitcoin_node_peers_total{job=\"Bitcoin-Fullnode\", network=\"$network\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks Sync Progress",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bitcoin_node_sync_progress_ratio{job=\"Bitcoin-Fullnode\", network=\"$network\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TxIndex Lag",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bitcoin_node_block_height{\n  job=\"Bitcoin-Fullnode\",\n  network=\"$network\"\n}\n-\nignoring(index)\nbitcoin_node_index_height{\n  job=\"Bitcoin-Fullnode\",\n  network=\"$network\",\n  index=\"txindex\"\n}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Filter Index Lag",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bitcoin_node_block_height{\n  job=\"Bitcoin-Fullnode\",\n  network=\"$network\"\n}\n-\nignoring(index)\nbitcoin_node_index_height{\n  job=\"Bitcoin-Fullnode\",\n  network=\"$network\",\n  index=\"basic_block_filter_index\"\n}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Download Lag",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bitcoin_node_header_height{job=\"Bitcoin-Fullnode\", network=\"$network\"}\n-\nbitcoin_node_block_height{job=\"Bitcoin-Fullnode\", network=\"$network\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block | Index Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "bitcoin_node_block_height{job=\"Bitcoin-Fullnode\", network=\"$network\"}",
     "legendFormat": "block-height"
    },
    {
     "expr": "bitcoin_node_header_height{job=\"Bitcoin-Fullnode\", network=\"$network\"}",
     "legendFormat": "header-height"
    },
    {
     "expr": "bitcoin_node_index_height{job=\"Bitcoin-Fullnode\", network=\"$network\", index=\"basic_block_filter_index\"}",
     "legendFormat": "basic-block-filter-index"
    },
    {
     "expr": "bitcoin_node_index_height{job=\"Bitcoin-Fullnode\", network=\"$network\", index=\"txindex\"}",
     "legendFormat": "tx-index"
    }
   ]
  },
  {
   "title": "Blocks Per Hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "increase(\n  bitcoin_node_block_height{\n    job=\"Bitcoin-Fullnode\",\n    network=\"$network\"\n  }[1h]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Hash Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "targets": [
    {
     "expr": "bitcoin_network_hash_rate_hashes_per_second{\n  job=\"Bitcoin-Fullnode\",\n  network=\"$network\",\n  window=\"12_blocks\"\n}",
     "legendFormat": "12-blocks"
    },
    {
     "expr": "bitcoin_network_hash_rate_hashes_per_second{\n  job=\"Bitcoin-Fullnode\",\n  network=\"$network\",\n  window=\"120_blocks\"\n}",
     "legendFormat": "120-blocks"
    },
    {
     "expr": "bitcoin_network_hash_rate_hashes_per_second{\n  job=\"Bitcoin-Fullnode\",\n  network=\"$network\",\n  window=\"2016_blocks\"\n}",
     "legendFormat": "2016-blocks"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "bitcoin_node_peers_total{job=\"Bitcoin-Fullnode\", network=\"$network\"}",
     "legendFormat": "total"
    },
    {
     "expr": "bitcoin_node_peers_inbound{job=\"Bitcoin-Fullnode\", network=\"$network\"}",
     "legendFormat": "inbound"
    },
    {
     "expr": "bitcoin_node_peers_outbound{job=\"Bitcoin-Fullnode\", network=\"$network\"}",
     "legendFormat": "outbound"
    },
    {
     "expr": "bitcoin_node_banned_peers{job=\"Bitcoin-Fullnode\", network=\"$network\"}",
     "legendFormat": "banned"
    }
   ]
  },
  {
   "title": "Estimated Fee Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "sat/vB" } },
   "targets": [
    {
     "expr": "bitcoin_node_estimated_fee_btc_per_kvb{\n  job=\"Bitcoin-Fullnode\",\n  network=\"$network\"\n} * 100000",
     "legendFormat": "{{target_blocks}} blocks"
    }
   ]
  },
  {
   "title": "Latest Block Fees ₿",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bitcoin_node_latest_block_fees_btc{job=\"Bitcoin-Fullnode\", network=\"$network\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Block Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bitcoin_node_latest_block_transactions{job=\"Bitcoin-Fullnode\", network=\"$network\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Block Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bitcoin_node_latest_block_timestamp_seconds{\n  job=\"Bitcoin-Fullnode\",\n  network=\"$network\"\n} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mempool Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bitcoin_node_mempool_memory_bytes{\n  job=\"Bitcoin-Fullnode\",\n  network=\"$network\"\n}\n/\nbitcoin_node_mempool_limit_bytes{\n  job=\"Bitcoin-Fullnode\",\n  network=\"$network\"\n}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mempool Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bitcoin_node_mempool_size_bytes{job=\"Bitcoin-Fullnode\", network=\"$network\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mempool Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bitcoin_node_mempool_transactions{job=\"Bitcoin-Fullnode\", network=\"$network\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}